[plugin]
name = "docker-plugin-demo"
description = "Just a demo"
version = "1.0"
maintainer_name = "Jeff Lindsay"
maintainer_email = "progrium@gmail.com"
website_url = "http://github.com/progrium/docker-plugins"

[plugin.config]

[plugin.compatibility]
